import { StatusBadge } from './StatusBadge.jsx';
import { formatCurrency, formatDate } from './ClaimList.jsx';

export function ClaimDetails({ claim, isLoading, error, onClose, onRetry }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="claim-details-title"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white shadow-xl sm:max-w-2xl sm:rounded-xl"><div className="flex items-start justify-between border-b border-slate-200 px-5 py-5 sm:px-7"><div><p className="font-mono text-xs font-semibold text-teal-700">{claim ? `Claim #${claim._id.slice(-8)}` : 'Claim details'}</p><h2 id="claim-details-title" className="mt-1 text-xl font-semibold text-slate-950">Claim details</h2></div><button type="button" onClick={onClose} aria-label="Close claim details" className="rounded-md p-2 text-xl leading-none text-slate-400 hover:bg-slate-100 hover:text-slate-700">×</button></div>{isLoading && <div className="px-6 py-16 text-center text-sm text-slate-500">Loading claim details…</div>}{error && <div className="px-6 py-12 text-center"><p className="text-sm text-red-600">{error}</p><button type="button" onClick={onRetry} className="mt-4 rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Retry</button></div>}{claim && !isLoading && !error && <ClaimContent claim={claim} />}</div></div>;
}

function ClaimContent({ claim }) {
  return <div className="space-y-6 px-5 py-6 sm:px-7"><div className="flex flex-wrap items-center justify-between gap-3"><StatusBadge status={claim.status} /><p className="text-sm text-slate-500">Submitted {formatDate(claim.submissionDate)}</p></div><div className="grid gap-4 sm:grid-cols-2"><Detail label="Patient name" value={claim.name} /><Detail label="Email" value={claim.email} /><Detail label="Claim amount" value={formatCurrency(claim.claimAmount)} /><Detail label="Approved amount" value={claim.approvedAmount !== null && claim.approvedAmount !== undefined ? formatCurrency(claim.approvedAmount) : 'Not decided'} /></div><div><h3 className="text-sm font-semibold text-slate-900">Description</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{claim.description}</p></div><div><h3 className="text-sm font-semibold text-slate-900">Insurer comments</h3><p className="mt-2 text-sm leading-6 text-slate-600">{claim.insurerComments || 'No comments have been added yet.'}</p></div><div className="border-t border-slate-100 pt-5"><h3 className="text-sm font-semibold text-slate-900">Supporting document</h3><a href={claim.document} target="_blank" rel="noreferrer" className="mt-2 inline-flex rounded-md border border-teal-200 bg-teal-50 px-3 py-2 text-sm font-semibold text-teal-800 hover:bg-teal-100">Open document in new tab</a></div></div>;
}

function Detail({ label, value }) { return <div className="rounded-lg bg-slate-50 px-4 py-3"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-medium text-slate-900">{value}</p></div>; }
