import { StatusBadge } from './StatusBadge.jsx';

export function ClaimList({ claims, onSelect }) {
  if (claims.length === 0) return <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center shadow-sm"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-teal-50 text-teal-700">+</div><h2 className="mt-4 text-base font-semibold text-slate-900">No claims submitted yet.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">When you submit a claim, you can track its review status and approved amount here.</p><button type="button" onClick={() => onSelect('new')} className="mt-5 rounded-md bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-teal-800">Submit your first claim</button></div>;
  return <div className="space-y-3">{claims.map((claim) => <ClaimCard key={claim._id} claim={claim} onSelect={onSelect} />)}</div>;
}

function ClaimCard({ claim, onSelect }) {
  return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-slate-300 hover:shadow-md"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => onSelect(claim._id)} className="font-mono text-xs font-semibold text-teal-700 hover:underline">#{claim._id.slice(-8)}</button><StatusBadge status={claim.status} /></div><h3 className="mt-3 line-clamp-2 text-sm font-semibold text-slate-900">{claim.description}</h3><p className="mt-1 text-xs text-slate-500">Submitted {formatDate(claim.submissionDate)}</p></div><div className="text-left sm:text-right"><p className="text-lg font-semibold text-slate-950">{formatCurrency(claim.claimAmount)}</p><p className="mt-1 text-xs text-slate-500">Claim amount</p></div></div><div className="mt-4 flex flex-col gap-3 border-t border-slate-100 pt-4 text-sm sm:flex-row sm:items-center sm:justify-between"><div className="text-slate-600">Approved amount: <span className="font-medium text-slate-900">{claim.approvedAmount !== null && claim.approvedAmount !== undefined ? formatCurrency(claim.approvedAmount) : 'Not decided'}</span></div><div className="flex items-center gap-4"><a href={claim.document} target="_blank" rel="noreferrer" className="text-sm font-medium text-teal-700 hover:text-teal-800 hover:underline">View document</a><button type="button" onClick={() => onSelect(claim._id)} className="text-sm font-semibold text-slate-700 hover:text-slate-950">View details</button></div></div></article>;
}

export const formatCurrency = (amount) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(amount);
export const formatDate = (date) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(date));
